<div id="termsDiv" style="display:inline-block;">
<h1>ZÁKLADNÍ SHRNUTÍ</h1>
 <p>Společnost PlanetOfGames 2022 s.r.o. provádí zpracování Vašich osobních údajů, neboť je to nezbytné pro splnění smlouvy s Vámi ohledně prodeje zboží (nebo pro provedení opatření přijatých před uzavřením takové smlouvy), a dále provádí zpracování Vašich osobních údajů, které je nezbytné pro plnění veřejnoprávních povinností této společnosti. </p>
<h2>1. TOTOŽNOST A KONTAKTNÍ ÚDAJE SPRÁVCE</h2>
<p> 1.1 Správcem Vašich osobních údajů je obchodní společnost PlanetOfGames 2022 s.r.o. se sídlem Neznámá 666/10 Ostrava 10900, identifikační číslo:010101010, zapsaná v obchodním rejstříku vedeném KS v Ostravě, oddíl C, vložka 11111 (dále jen „správce“).</p> 
<p>1.2 Kontaktní údaje správce jsou následující: adresa pro doručování Neznámá 666/10 Ostrava 10900, adresa elektronické pošty vymysleny.mail@seznam.cz, telefon 111222333.</p>
<p> 1.3 Správce nejmenoval pověřence pro ochranu osobních údajů. </p>
<h2>2. PRÁVNÍ ZÁKLAD ZPRACOVÁNÍ OSOBNÍCH ÚDAJŮ</h2>
        <p>2.1 Právním základem zpracování Vašich osobních údajů je skutečnost, že toto zpracování je nezbytné pro:</p> 
        <p>2.1.1 splnění smlouvy mezi Vámi a správcem nebo pro provedení opatření správcem před uzavřením takové smlouvy ve smyslu čl. 6 odst. 1 písm. b) Nařízení Evropského parlamentu a Rady 2016/679 o ochraně fyzických osob v souvislosti se zpracováním osobních údajů a o volném pohybu těchto údajů a o zrušení směrnice 95/46/ES (obecné nařízení o ochraně osobních údajů) (dále jen „nařízení“);</p> 
        <p>2.1.2 splnění právních povinností, které se na správce vztahují, ve smyslu čl. 6 odst. 1 písm. c) nařízení, a to konkrétně zejména splnění povinností uložených správci obecně závaznými právními předpisy, zejména zákonem č. 235/2004 Sb., o dani z přidané hodnoty, ve znění pozdějších předpisů, zákonem č. 586/1992 Sb., o daních z příjmů, ve znění pozdějších předpisů, a zákonem č. 563/1991 Sb., o účetnictví, ve znění pozdějších předpisů.</p>
<h2>3. ÚČEL ZPRACOVÁNÍ OSOBNÍCH ÚDAJŮ</h2>
<p>3.1 Účelem zpracování Vašich osobních údajů je plnění smlouvy mezi Vámi a správcem, včetně doručení zboží a řešení práv z odpovědnosti za vady, či provedení opatření správcem před uzavřením takové smlouvy a dále plnění souvisejících veřejnoprávních povinností správcem.</p> 
<p>3.2 Ze strany správce nedochází k automatickému individuálnímu rozhodování ve smyslu čl. 22 nařízení.</p> 
<h2>4. DOBA ULOŽENÍ OSOBNÍCH ÚDAJŮ</h2>
<p>4.1 Vaše osobní údaje budou zpracovávány po dobu trvání účinků práv a povinností ze smlouvy a dále po dobu nutnou pro účely archivování podle příslušných obecně závazných právních předpisů, nejdéle však po dobu stanovenou obecně závaznými právními předpisy.</p>
<h2>5. DALŠÍ PŘÍJEMCI OSOBNÍCH ÚDAJŮ</h2>
<p>5.1 Dalšími příjemci Vašich osobních údajů budou zasílatelské společnosti a jiné osoby podílející se na dodání zboží či realizaci plateb na základě kupní smlouvy, a osoby zajišťující pro správce technické služby související s provozem e-shopu, včetně provozu software a ukládání dat.</p> 
<p>5.2 Příjemci Vašich osobních údajů zpracovávaných za účelem plnění povinností vyplývajících z právních předpisů můžou být dále orgány finanční správy či jiné příslušné úřady v případech, kdy tak správci ukládají obecně závazné právní předpisy.</p> 
<p>5.3 Správce nemá v úmyslu předat Vaše osobní údaje do třetí země (do země mimo EU) nebo mezinárodní organizaci.</p>
<h2>6. PRÁVA SUBJEKTU ÚDAJŮ</h2>
<p>6.1 Za podmínek stanovených v nařízení máte právo požadovat od správce přístup k Vašim osobním údajům, právo na opravu nebo výmaz Vašich osobních údajů, popřípadě omezení jejich zpracování, právo vznést námitku proti zpracování Vašich osobních údajů a dále právo na přenositelnost Vašich osobních údajů.</p> 
<p>6.2 Pokud byste se domníval(a), že zpracováním Vašich osobních údajů bylo porušeno či je porušováno nařízení, máte mimo jiné právo podat stížnost u dozorového úřadu.</p> 
<p>6.3 Nemáte povinnost osobní údaje poskytnout. Poskytnutí Vašich osobních údajů je nutným požadavkem pro uzavření a plnění smlouvy a bez poskytnutí Vašich osobních údajů není možné smlouvu uzavřít či ji ze strany správce splnit.</p>
</div>
