<?php if(isset($_SESSION["user"]) && $_SESSION["user"]["role"] == "admin"): ?>
<div class="row" style="margin-top: 5em; margin-left: -8%; margin-right: -8%;">
<div id="adminMenu" class="col-md-3">
    <?php if (isset($action)): ?> 
    <div style="color:green; margin-left: 20px;"><?= $action ?></div>
    <?php endif; ?>
  <div style="font-size: 25px; margin-left: 20px;">Menu:</div>
  <button onclick="displayProductMenu()">Správa produktů</button><br><br>
  <button onclick="displayOrderMenu()">Správa objednávek</button><br><br>
</div>        
<div class="col-md-8" id="adminContent">
    <div id="productMenu">
        <div id="searchProduct">
            <form action="">
                <input onkey onkeyup="searchP(this.value)" style="margin-left: 30px; width:60%; height:45px; padding: 10px;" type="text" name="search_p_name" placeholder="Vyhledat produkt podle názvu">
            </form>
        </div>
        <div style="margin-top: 30px; text-align: center; margin-right:33%"><a class="button_big" href="admin/add">Přidat produkt</a></div>
        <div id="adminProducts"></div>
    </div>
    <div id="orderMenu">
        <div id="searchOrder">
            <form action="">
                <input onkey onkeyup="searchO(this.value)" style="margin-left: 30px; width:60%; height:45px; padding: 10px;" type="text" name="search_o_id" placeholder="Vyhledat objednávku podle ID">
            </form>
        </div>
        <div id="adminOrders"></div>
    </div>
</div>
</div>
<?php endif; ?>
<script>        
    displayProductMenu();
    function displayProductMenu()
    {
        searchP("");
        document.getElementById("productMenu").style.display = "block";
        document.getElementById("orderMenu").style.display = "none";
    }
    function displayOrderMenu()
    {
        searchO("");
        document.getElementById("productMenu").style.display = "none";
        document.getElementById("orderMenu").style.display = "block";
    }
    function searchP(str)
    {
        var xhttp;
        xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function(){
            if (this.readyState == 4 && this.status == 200){
                document.getElementById("adminProducts").innerHTML = this.responseText;
            }
        };
        xhttp.open("GET", "search/pAdmin?key="+str, true);
        xhttp.send();
    }
    function searchO(str)
    {
        var xhttp;
        xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function(){
            if (this.readyState == 4 && this.status == 200){
                document.getElementById("adminOrders").innerHTML = this.responseText;
            }
        };
        xhttp.open("GET", "search/oAdmin?key="+str, true);
        xhttp.send();
    }
</script>