<div class="container" id="account">
    <div class="col-md-3" style="float:left;">
<?= $_SESSION["user"]["name"] ?> <?= $_SESSION["user"]["surname"] ?>
<ul>
    <li><a href="account">Objednávky</a></li>
    <li><a href="account?p=2">Úprava osobních údajů</a></li>
    <li><a href="account?p=3">Změna hesla</a></li>
    <li><a href="account?p=4" onclick="return confirm('Přejete si smazat účet? (akci nelze vrátit)')">Smazat účet</a></li>
</ul>
    </div>
    <div class="profilePanel" style="margin-left:20%;">
        
       <?php if (!isset($_GET["p"]) && $orders): ?>
        <!-- SHOW USER ORDERS -->
        <table id="tableOrders">
        <tr>
            <th>Číslo</th>
            <th>Datum</th>
            <th>Cena (s DPH)</th>
            <th>Stav</th>
        </tr> 
        <?php foreach($orders as $value): ?>
        <tr>
            <td><a href="account?p=1&o=<?= $value["idOrder"] ?>"><?= $value["idOrder"]?></a></td>
            <td><?= $value["created_at"] ?></td>
            <td><?= $value["price_sum"] ?>,- Kč</td>
            <td><?= $value["status"] ?></td>
        </tr>
        <?php endforeach; ?>
        </table>               
       <?php endif;?>
        
    </div>
</div>