<div class="container" id="account">
    <div class="col-md-3" style="float:left;">
<?= $_SESSION["user"]["name"] ?> <?= $_SESSION["user"]["surname"] ?>
<ul>
    <li><a href="account">Objednávky</a></li>
    <li><a href="account?p=2">Úprava osobních údajů</a></li>
    <li><a href="account?p=3">Změna hesla</a></li>
    <li><a href="account?p=4" onclick="return confirm('Přejete si smazat účet? (akci nelze vrátit)')">Smazat účet</a></li>
</ul>
    </div>
    <div class="profilePanel">

<form method="post" action="account/password" class="container col-md-5">
    <div class="form-floating col-md-6">
        <input type="password"
               id="password_old"
               name="password_old"
               class="form-control"
               placeholder="Aktuální heslo"
               required>
        <label for="password_old" style="<?php if(isset($msg_pass_old_notmatch)) echo("color:red"); ?>">
         <?php if(isset($msg_pass_old_notmatch)) echo ($msg_pass_old_notmatch); else echo ("Aktuální heslo"); ?></label>
    </div><br>
    <div class="form-floating col-md-6">        
        <input type="password"
               id="password"
               name="password"
               class="form-control"
               pattern=".{8,}" title="Heslo musí mít alespoň 8 znaků, jedno velké a jedno malé písmeno a jednu číslici."
               placeholder="Heslo"
               required>   
        <label for="password" style="<?php if(isset($msg_pass_invalid)) echo("color:red"); ?>">
            <?php if(isset($msg_pass_invalid)) echo ($msg_pass_invalid); else echo ("Heslo"); ?></label>
    </div><br>
    <div class="form-floating col-md-6">        
        <input type="password"
               id="password_again"
               name="password_again"
               class="form-control"
               pattern=".{8,}" title="Heslo musí mít alespoň 8 znaků, jedno velké a jedno malé písmeno a jednu číslici."
               placeholder="Heslo znovu"
               required>   
        <label for="password_again" style="<?php if(isset($msg_pass_notmatch)) echo("color:red"); ?>">
            <?php if(isset($msg_pass_notmatch)) echo ($msg_pass_notmatch); else echo ("Heslo znovu"); ?></label>
    </div><br>
    <input  class="button-medium" type="submit" value="Uložit">
</form>
</div>
</div>