<div id="platformDiv" class="container col-md-12">
    <div class="row">
        <a class="col-md-3" href="home/PC">PC</a>
        <a class="col-md-3" href="home/XBOX">XBOX</a>
        <a class="col-md-3" href="home/PLAYSTATION">PLAYSTATION</a>
        <a class="col-md-3" href="home/SWITCH">SWITCH</a>
    </div>
</div>  

<div id="mainPage">

    <div class="slideshow-container">
        <div class="mySlides">
            <div class="numbertext">1 / 3</div>
            <img src="../imgs/carousel/dead_island2.jpg" style="width:100%">
        </div>

        <div class="mySlides">
            <div class="numbertext">2 / 3</div>
            <img src="../imgs/carousel/minecraft.jpg" style="width:100%">
        </div>

        <div class="mySlides">
            <div class="numbertext">3 / 3</div>
            <img src="../imgs/carousel/sw_jedi.jpg" style="width:100%">
        </div>
    </div>
    <?php if ($newGames): ?>
    <h3 style="margin-left:15%;">Novinky:</h3>
        <div id="productsNewest">            
            <div class="row">                
                <?php foreach ($newGames as $value): ?>
                    <div id="singleProduct" class="col-md-2">
                        <div id="productImg"><a href="product/<?= $value["url"] ?>">
                                <img src="imgs/<?= $value["image"] ?>" alt="<?= $value["image"] ?>"
                                     width="100" height="130"></a>
                        </div>
                        <!--<div><strong><?= $value["name"] ?> (<?= $value["platform"] ?>)</strong></div>-->
                        <?php if ($value["stock"] > 1 && $value["stock"] > 10): ?>
                            <div style="color:green">Skladem (>10ks)</div>
                        <?php elseif ($value["stock"] > 0): ?>
                            <div style="color:green">Skladem (<?= $value["stock"] ?>ks)</div>
                        <?php else: ?>
                            <div style="color:red">Není skladem</div>
                        <?php endif; ?>
                        <div><?= $value["price_dph"] ?>,- Kč</div>
                        <div>
                            <?php if ($value["stock"] > 0): ?> 
                                <a href="cart/add/<?= $value["url"] ?>?p=" class="button" id="buyButton">Koupit</a>
                            <?php endif; ?>                            
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <div id="productsDiv" class="col-md-12">
        <div class="row">
            <h3>Doporučené hry:</h3>
            <?php if ($games): ?>
                <?php foreach ($games as $value): ?>

                    <div id="singleProduct" class="col-md-3">                        
                        <div id="productImg"><a href="product/<?= $value["url"] ?>">
                                <img src="imgs/<?= $value["image"] ?>" alt="<?= $value["image"] ?>"
                                     width="100" height="130"></a></div>
                        <div><strong><?= $value["name"] ?> (<?= $value["platform"] ?>)</strong></div>
                        <div><!--Žánr: --><?= $value["genre"] ?></div>
                        <div><!--Typ hry: --><?= $value["game_type"] ?></div>
                        <?php if ($value["stock"] > 1 && $value["stock"] > 10): ?>
                            <div style="color:green">Skladem (>10ks)</div>
                        <?php elseif ($value["stock"] > 0): ?>
                            <div style="color:green">Skladem (<?= $value["stock"] ?>ks)</div>
                        <?php else: ?>
                            <div style="color:red">Není skladem</div>
                        <?php endif; ?>
                        <div><!--Cena: --><?= $value["price_dph"] ?>,- Kč</div>
                        <!--<div>(bez DPH: <?= $value["price"] ?>,- Kč)</div>-->                        
                        <div>
                            <?php if ($value["stock"] > 0): ?> 
                                <a href="cart/add/<?= $value["url"] ?>?p=" class="button" id="buyButton">Koupit</a>
                            <?php endif; ?>
                            <a href="product/<?= $value["url"] ?>">Více</a></div>
                    </div>
                <?php endforeach; ?>                      
            <?php else: ?>
                <div style="text-align:center;"><h2 style="margin-bottom: 1em; margin-top: 2em; margin-left: 2em;">Produkt nenalezen</h2></div>
            <?php endif; ?>
        </div>
    </div>
</div>
</div>
</div>
<script>
    var slideIndex = 0;
    showSlides();

    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("mySlides");

        for (i = 0; i < slides.length; i++)
            slides[i].style.display = "none";

        slideIndex++;
        if (slideIndex > slides.length)
            slideIndex = 1;
        slides[slideIndex - 1].style.display = "block";
        setTimeout(showSlides, 5000); // Change image every 5 seconds
    }
</script>